#!/bin/sh /etc/rc.common

export LD_LIBRARY_PATH=/lib/qtlib
export QT_QWS_FONTDIR=/lib/qtlib/fonts
export QWS_DISPLAY=Transformed:Rot90

export TSLIB_TSDEVICE=/dev/input/event3
export TSLIB_CONFFILE=/etc/ts.conf
export TSLIB_PLUGINDIR=/lib/qtlib/ts
export TSLIB_CALIBFILE=/etc/pointercal
export TSLIB_CONSOLEDEVICE=none
export TSLIB_FBDEVICE=/dev/fb0
export QWS_MOUSE_PROTO=tslib:/dev/input/event3